name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  beautiful_soup_dart: ^0.3.0
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.3.0
  http: ^1.2.2
  media_kit:
  media_kit_video:
  media_kit_libs_video:
  path_provider: ^2.1.5
  provider: ^6.1.2
  flutter_slidable: ^3.1.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  file_picker: ^9.0.2
  equatable: ^2.0.7
  saf_util: ^0.7.0
  saf_stream: ^0.11.2
  dio: ^5.8.0+1
  flutter_hls_parser: ^2.0.1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/